### ISSUE TITLE
Asking for further devleopment

### ISSUE THREAD

**Issue by stamerf** [fiwl-js/fiwl-js#6]
Dear thor,

I read your article, and I have the some problem with html. I love your project. Can you please go on with it? Also I don't understand how I can support this project. The given link seem to me to give no support possibility other then following.  

Best regards

**Comment by yummyweb** [comment]
Hi! Thanks for sharing your interest in FIWL. We are in the process of transferring ownership and revamping FIWL. Currently, starring the repo will suffice. When we will be in need of support, we will let you know.

Thanks,
yum
